# Generated by Django 3.2.16 on 2022-11-29 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='accound',
            new_name='account',
        ),
    ]
