# Generated by Django 3.2.16 on 2022-12-04 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_rename_accound_userinfo_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用戶名')),
                ('password', models.CharField(max_length=64, verbose_name='密碼')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(1, '緊急'), (2, '重要'), (3, '臨時')], default=1, verbose_name='級別')),
                ('title', models.CharField(max_length=64, verbose_name='標題')),
                ('detail', models.TextField(verbose_name='詳細訊息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='負責人')),
            ],
        ),
    ]
